### ISSUE TITLE
How to generate the stylometric features?

### ISSUE THREAD

**Issue by xiaopi-ouo** [piotrmp/fakestyle#1]
Hi, I want to generate the features to test the stylometric classifier.
Here is the main function in `NewsFeatures`
```
	public static void main(String[] args) throws IOException, ClassNotFoundException, ClassCastException {
		String corpusPath = args[0];
		String topicsPath = args[1];
		String annotationCachePath = args[2];
		String giExtendedPath = args[3];
		String corpusSourcesPath = args[4];
		String outPath = args[5];
		mainTopics(corpusPath, topicsPath);
		mainAnnotate(corpusPath, annotationCachePath);
		mainFeatures(corpusPath, annotationCachePath, topicsPath, giExtendedPath, corpusSourcesPath, outPath);
	}
```
There are 5 arguments must be assigned but I can just guess the `giExtendedPath` should be the path to `/NewsFeatures/resources/GI_extended.tsv` .
How about the other path? What format these files should be in?
Could you give me some example to show how to use it?
Many thanks!

**Comment by piotrmp** [comment]
1) `corpusPath` points to the folder containing corpus downloaded using `NewsStyleCorpus/CredibilityCorpusDownloader.java` or another corpus in the same format,
2) `topicsPath` and `annotationCachePath` point to empty folders to store intermediate results (LDA model and CoreNLP annotations)
3) `giExtendedPath`, as you've guessed, points to the location of `GI_extended.tsv` (or another dictionary in the same format)
4) `corpusSourcesPath` points to the location of  `corpusSources.tsv` (in the repo in `NewsStyleCorpus`)
5) `out` is the (initially) empty folder to store the feature output.
